name: ml_hw1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - seaborn
  - pip
  - xgboost
  - lightgbm
  - pip:
      - shap
      - lime

prefix: /opt/anaconda3/envs/ml_hw1